package types

// ArtistHomepageData 获取歌手详细API返回数据
type ArtistHomepageData struct {
	RawJson string `json:"-"`
	Code    int    `json:"code"`
	Data    struct {
		Cursor string `json:"cursor"`
		Blocks []struct {
			ShowType  string      `json:"showType"`
			Alg       string      `json:"alg"`
			Scm       string      `json:"scm"`
			Id        string      `json:"id"`
			AdInfo    interface{} `json:"adInfo"`
			ExtInfo   interface{} `json:"extInfo"`
			Position  string      `json:"position"`
			Md5       interface{} `json:"md5"`
			Channel   string      `json:"channel"`
			UiElement struct {
				MainTitle struct {
					Title       string      `json:"title"`
					TitleImgId  interface{} `json:"titleImgId"`
					TitleImgUrl interface{} `json:"titleImgUrl"`
					Action      interface{} `json:"action"`
				} `json:"mainTitle"`
				SubTitles []struct {
					Title       string      `json:"title"`
					TitleImgId  interface{} `json:"titleImgId"`
					TitleImgUrl interface{} `json:"titleImgUrl"`
					Action      interface{} `json:"action"`
				} `json:"subTitles"`
				Images       interface{} `json:"images"`
				Labels       interface{} `json:"labels"`
				TextLinks    interface{} `json:"textLinks"`
				Descriptions interface{} `json:"descriptions"`
				Icons        interface{} `json:"icons"`
				Buttons      interface{} `json:"buttons"`
				Videos       interface{} `json:"videos"`
				Superscript  interface{} `json:"superscript"`
				Type         interface{} `json:"type"`
				CoverTagVO   interface{} `json:"coverTagVO"`
			} `json:"uiElement"`
			Code      string `json:"code"`
			Creatives []struct {
				Id           interface{} `json:"id"`
				BlockId      interface{} `json:"blockId"`
				CreativeId   interface{} `json:"creativeId"`
				CreativeType string      `json:"creativeType"`
				Position     string      `json:"position"`
				Action       struct {
					ClickAction struct {
						Action    int    `json:"action"`
						TargetUrl string `json:"targetUrl"`
					} `json:"clickAction"`
				} `json:"action"`
				UiElement interface{} `json:"uiElement"`
				AdInfo    interface{} `json:"adInfo"`
				Code      interface{} `json:"code"`
				Resources []struct {
					ResourceType    string      `json:"resourceType"`
					ResourceId      string      `json:"resourceId"`
					ResourceUrl     interface{} `json:"resourceUrl"`
					ResourceExtInfo struct {
						CommentCount int `json:"commentCount,omitempty"`
						PlayCount    int `json:"playCount"`
						Users        []struct {
							DefaultAvatar       bool        `json:"defaultAvatar"`
							Province            int         `json:"province"`
							AuthStatus          int         `json:"authStatus"`
							Followed            bool        `json:"followed"`
							AvatarUrl           string      `json:"avatarUrl"`
							AccountStatus       int         `json:"accountStatus"`
							Gender              int         `json:"gender"`
							City                int         `json:"city"`
							Birthday            int64       `json:"birthday"`
							UserId              int         `json:"userId"`
							UserType            int         `json:"userType"`
							Nickname            string      `json:"nickname"`
							Signature           string      `json:"signature"`
							Description         string      `json:"description"`
							DetailDescription   string      `json:"detailDescription"`
							AvatarImgId         int64       `json:"avatarImgId"`
							BackgroundImgId     int64       `json:"backgroundImgId"`
							BackgroundUrl       string      `json:"backgroundUrl"`
							Authority           int         `json:"authority"`
							Mutual              bool        `json:"mutual"`
							ExpertTags          interface{} `json:"expertTags"`
							Experts             interface{} `json:"experts"`
							DjStatus            int         `json:"djStatus"`
							VipType             int         `json:"vipType"`
							RemarkName          interface{} `json:"remarkName"`
							AuthenticationTypes int         `json:"authenticationTypes"`
							AvatarDetail        interface{} `json:"avatarDetail"`
							AvatarImgIdStr      string      `json:"avatarImgIdStr"`
							Anchor              bool        `json:"anchor"`
							BackgroundImgIdStr  string      `json:"backgroundImgIdStr"`
							AvatarImgIdStr1     string      `json:"avatarImgId_str"`
							Brand               string      `json:"brand,omitempty"`
						} `json:"users"`
						DjRadioId       int    `json:"djRadioId,omitempty"`
						DjRadioName     string `json:"djRadioName,omitempty"`
						DjRadioPrograms []struct {
							MainSong struct {
								Name        string        `json:"name"`
								Id          int           `json:"id"`
								Position    int           `json:"position"`
								Alias       []interface{} `json:"alias"`
								Status      int           `json:"status"`
								Fee         int           `json:"fee"`
								CopyrightId int           `json:"copyrightId"`
								Disc        string        `json:"disc"`
								No          int           `json:"no"`
								Artists     []struct {
									Name        string        `json:"name"`
									Id          int           `json:"id"`
									PicId       int           `json:"picId"`
									Img1V1Id    int           `json:"img1v1Id"`
									BriefDesc   string        `json:"briefDesc"`
									PicUrl      string        `json:"picUrl"`
									Img1V1Url   string        `json:"img1v1Url"`
									AlbumSize   int           `json:"albumSize"`
									Alias       []interface{} `json:"alias"`
									Trans       string        `json:"trans"`
									MusicSize   int           `json:"musicSize"`
									TopicPerson int           `json:"topicPerson"`
								} `json:"artists"`
								Album struct {
									Name        string      `json:"name"`
									Id          int         `json:"id"`
									Type        interface{} `json:"type"`
									Size        int         `json:"size"`
									PicId       int64       `json:"picId"`
									BlurPicUrl  string      `json:"blurPicUrl"`
									CompanyId   int         `json:"companyId"`
									Pic         int64       `json:"pic"`
									PicUrl      string      `json:"picUrl"`
									PublishTime int         `json:"publishTime"`
									Description string      `json:"description"`
									Tags        string      `json:"tags"`
									Company     interface{} `json:"company"`
									BriefDesc   string      `json:"briefDesc"`
									Artist      struct {
										Name        string        `json:"name"`
										Id          int           `json:"id"`
										PicId       int           `json:"picId"`
										Img1V1Id    int           `json:"img1v1Id"`
										BriefDesc   string        `json:"briefDesc"`
										PicUrl      string        `json:"picUrl"`
										Img1V1Url   string        `json:"img1v1Url"`
										AlbumSize   int           `json:"albumSize"`
										Alias       []interface{} `json:"alias"`
										Trans       string        `json:"trans"`
										MusicSize   int           `json:"musicSize"`
										TopicPerson int           `json:"topicPerson"`
									} `json:"artist"`
									Songs           []interface{} `json:"songs"`
									Alias           []interface{} `json:"alias"`
									Status          int           `json:"status"`
									CopyrightId     int           `json:"copyrightId"`
									CommentThreadId string        `json:"commentThreadId"`
									Artists         []struct {
										Name        string        `json:"name"`
										Id          int           `json:"id"`
										PicId       int           `json:"picId"`
										Img1V1Id    int           `json:"img1v1Id"`
										BriefDesc   string        `json:"briefDesc"`
										PicUrl      string        `json:"picUrl"`
										Img1V1Url   string        `json:"img1v1Url"`
										AlbumSize   int           `json:"albumSize"`
										Alias       []interface{} `json:"alias"`
										Trans       string        `json:"trans"`
										MusicSize   int           `json:"musicSize"`
										TopicPerson int           `json:"topicPerson"`
									} `json:"artists"`
									SubType   interface{} `json:"subType"`
									TransName interface{} `json:"transName"`
									OnSale    bool        `json:"onSale"`
									Mark      int         `json:"mark"`
									PicIdStr  string      `json:"picId_str"`
								} `json:"album"`
								Starred              bool          `json:"starred"`
								Popularity           float64       `json:"popularity"`
								Score                int           `json:"score"`
								StarredNum           int           `json:"starredNum"`
								Duration             int           `json:"duration"`
								PlayedNum            int           `json:"playedNum"`
								DayPlays             int           `json:"dayPlays"`
								HearTime             int           `json:"hearTime"`
								Ringtone             interface{}   `json:"ringtone"`
								Crbt                 interface{}   `json:"crbt"`
								Audition             interface{}   `json:"audition"`
								CopyFrom             string        `json:"copyFrom"`
								CommentThreadId      string        `json:"commentThreadId"`
								RtUrl                interface{}   `json:"rtUrl"`
								Ftype                int           `json:"ftype"`
								RtUrls               []interface{} `json:"rtUrls"`
								Copyright            int           `json:"copyright"`
								TransName            interface{}   `json:"transName"`
								Sign                 interface{}   `json:"sign"`
								Mark                 int           `json:"mark"`
								OriginCoverType      int           `json:"originCoverType"`
								OriginSongSimpleData interface{}   `json:"originSongSimpleData"`
								Single               int           `json:"single"`
								NoCopyrightRcmd      interface{}   `json:"noCopyrightRcmd"`
								HMusic               struct {
									Name        string  `json:"name"`
									Id          int64   `json:"id"`
									Size        int     `json:"size"`
									Extension   string  `json:"extension"`
									Sr          int     `json:"sr"`
									DfsId       int     `json:"dfsId"`
									Bitrate     int     `json:"bitrate"`
									PlayTime    int     `json:"playTime"`
									VolumeDelta float64 `json:"volumeDelta"`
								} `json:"hMusic"`
								MMusic struct {
									Name        string  `json:"name"`
									Id          int64   `json:"id"`
									Size        int     `json:"size"`
									Extension   string  `json:"extension"`
									Sr          int     `json:"sr"`
									DfsId       int     `json:"dfsId"`
									Bitrate     int     `json:"bitrate"`
									PlayTime    int     `json:"playTime"`
									VolumeDelta float64 `json:"volumeDelta"`
								} `json:"mMusic"`
								LMusic struct {
									Name        string  `json:"name"`
									Id          int64   `json:"id"`
									Size        int     `json:"size"`
									Extension   string  `json:"extension"`
									Sr          int     `json:"sr"`
									DfsId       int     `json:"dfsId"`
									Bitrate     int     `json:"bitrate"`
									PlayTime    int     `json:"playTime"`
									VolumeDelta float64 `json:"volumeDelta"`
								} `json:"lMusic"`
								BMusic struct {
									Name        string  `json:"name"`
									Id          int64   `json:"id"`
									Size        int     `json:"size"`
									Extension   string  `json:"extension"`
									Sr          int     `json:"sr"`
									DfsId       int     `json:"dfsId"`
									Bitrate     int     `json:"bitrate"`
									PlayTime    int     `json:"playTime"`
									VolumeDelta float64 `json:"volumeDelta"`
								} `json:"bMusic"`
								Mp3Url interface{} `json:"mp3Url"`
								Rurl   interface{} `json:"rurl"`
								Rtype  int         `json:"rtype"`
								Mvid   int         `json:"mvid"`
							} `json:"mainSong"`
							Songs interface{} `json:"songs"`
							Dj    struct {
								DefaultAvatar       bool        `json:"defaultAvatar"`
								Province            int         `json:"province"`
								AuthStatus          int         `json:"authStatus"`
								Followed            bool        `json:"followed"`
								AvatarUrl           string      `json:"avatarUrl"`
								AccountStatus       int         `json:"accountStatus"`
								Gender              int         `json:"gender"`
								City                int         `json:"city"`
								Birthday            int64       `json:"birthday"`
								UserId              int         `json:"userId"`
								UserType            int         `json:"userType"`
								Nickname            string      `json:"nickname"`
								Signature           string      `json:"signature"`
								Description         string      `json:"description"`
								DetailDescription   string      `json:"detailDescription"`
								AvatarImgId         int64       `json:"avatarImgId"`
								BackgroundImgId     int64       `json:"backgroundImgId"`
								BackgroundUrl       string      `json:"backgroundUrl"`
								Authority           int         `json:"authority"`
								Mutual              bool        `json:"mutual"`
								ExpertTags          interface{} `json:"expertTags"`
								Experts             interface{} `json:"experts"`
								DjStatus            int         `json:"djStatus"`
								VipType             int         `json:"vipType"`
								RemarkName          interface{} `json:"remarkName"`
								AuthenticationTypes int         `json:"authenticationTypes"`
								AvatarDetail        interface{} `json:"avatarDetail"`
								AvatarImgIdStr      string      `json:"avatarImgIdStr"`
								Anchor              bool        `json:"anchor"`
								BackgroundImgIdStr  string      `json:"backgroundImgIdStr"`
								AvatarImgIdStr1     string      `json:"avatarImgId_str"`
								Brand               string      `json:"brand"`
							} `json:"dj"`
							BlurCoverUrl interface{} `json:"blurCoverUrl"`
							Radio        struct {
								Id                    int         `json:"id"`
								Dj                    interface{} `json:"dj"`
								Name                  string      `json:"name"`
								PicUrl                string      `json:"picUrl"`
								Desc                  string      `json:"desc"`
								SubCount              int         `json:"subCount"`
								ProgramCount          int         `json:"programCount"`
								CreateTime            int64       `json:"createTime"`
								CategoryId            int         `json:"categoryId"`
								Category              string      `json:"category"`
								SecondCategoryId      int         `json:"secondCategoryId"`
								SecondCategory        string      `json:"secondCategory"`
								RadioFeeType          int         `json:"radioFeeType"`
								FeeScope              int         `json:"feeScope"`
								Buyed                 bool        `json:"buyed"`
								Videos                interface{} `json:"videos"`
								Finished              bool        `json:"finished"`
								UnderShelf            bool        `json:"underShelf"`
								PurchaseCount         int         `json:"purchaseCount"`
								Price                 int         `json:"price"`
								OriginalPrice         int         `json:"originalPrice"`
								DiscountPrice         interface{} `json:"discountPrice"`
								LastProgramCreateTime int64       `json:"lastProgramCreateTime"`
								LastProgramName       interface{} `json:"lastProgramName"`
								LastProgramId         int         `json:"lastProgramId"`
								PicId                 int64       `json:"picId"`
								RcmdText              interface{} `json:"rcmdText"`
								HightQuality          bool        `json:"hightQuality"`
								WhiteList             bool        `json:"whiteList"`
								LiveInfo              interface{} `json:"liveInfo"`
								PlayCount             int         `json:"playCount"`
								Icon                  interface{} `json:"icon"`
								Privacy               bool        `json:"privacy"`
								IntervenePicUrl       string      `json:"intervenePicUrl"`
								IntervenePicId        int64       `json:"intervenePicId"`
								Dynamic               bool        `json:"dynamic"`
								ShortName             string      `json:"shortName"`
								TaskId                int         `json:"taskId"`
								ComposeVideo          bool        `json:"composeVideo"`
							} `json:"radio"`
							SubscribedCount      int           `json:"subscribedCount"`
							Reward               bool          `json:"reward"`
							MainTrackId          int           `json:"mainTrackId"`
							SerialNum            int           `json:"serialNum"`
							ListenerCount        int           `json:"listenerCount"`
							Name                 string        `json:"name"`
							Id                   int           `json:"id"`
							CreateTime           int64         `json:"createTime"`
							Description          string        `json:"description"`
							UserId               int           `json:"userId"`
							CoverUrl             string        `json:"coverUrl"`
							CommentThreadId      string        `json:"commentThreadId"`
							Channels             []interface{} `json:"channels"`
							Titbits              interface{}   `json:"titbits"`
							TitbitImages         interface{}   `json:"titbitImages"`
							PubStatus            int           `json:"pubStatus"`
							TrackCount           int           `json:"trackCount"`
							BdAuditStatus        int           `json:"bdAuditStatus"`
							ProgramFeeType       int           `json:"programFeeType"`
							Buyed                bool          `json:"buyed"`
							ProgramDesc          interface{}   `json:"programDesc"`
							H5Links              []interface{} `json:"h5Links"`
							CoverId              int64         `json:"coverId"`
							AdjustedPlayCount    float64       `json:"adjustedPlayCount"`
							CanReward            bool          `json:"canReward"`
							AuditStatus          int           `json:"auditStatus"`
							UpdateTime           int64         `json:"updateTime"`
							CategoryId           int           `json:"categoryId"`
							Category             string        `json:"category"`
							SecondCategoryId     int           `json:"secondCategoryId"`
							SecondCategory       string        `json:"secondCategory"`
							ScheduledPublishTime int64         `json:"scheduledPublishTime"`
							Privacy              bool          `json:"privacy"`
							DisPlayStatus        string        `json:"disPlayStatus"`
							CreateEventId        int           `json:"createEventId"`
							Duration             int           `json:"duration"`
							Publish              bool          `json:"publish"`
						} `json:"djRadioPrograms,omitempty"`
						ThreadId       string `json:"threadId,omitempty"`
						SubCount       int    `json:"subCount,omitempty"`
						DjProgramCount int    `json:"djProgramCount,omitempty"`
						RadioFeeType   int    `json:"radioFeeType,omitempty"`
						RadioFeeScope  int    `json:"radioFeeScope,omitempty"`
					} `json:"resourceExtInfo"`
					ResourceExt struct {
						LikeCount int  `json:"likeCount,omitempty"`
						Liked     bool `json:"liked,omitempty"`
						Song      struct {
							Name  string `json:"name"`
							Id    int    `json:"id"`
							Album struct {
								Name   string `json:"name"`
								Id     int    `json:"id"`
								PicUrl string `json:"picUrl"`
							} `json:"album"`
							Artists []struct {
								Name   string `json:"name"`
								Id     int    `json:"id"`
								PicUrl string `json:"picUrl"`
							} `json:"artists"`
						} `json:"song,omitempty"`
						ThreadId        string `json:"threadId,omitempty"`
						IsSelf          bool   `json:"isSelf,omitempty"`
						SpecialType     int    `json:"specialType"`
						LineNumber      string `json:"lineNumber,omitempty"`
						HighQuality     bool   `json:"highQuality,omitempty"`
						Privacy         bool   `json:"privacy,omitempty"`
						UserProfileData struct {
							DefaultAvatar       bool        `json:"defaultAvatar"`
							Province            int         `json:"province"`
							AuthStatus          int         `json:"authStatus"`
							Followed            bool        `json:"followed"`
							AvatarUrl           string      `json:"avatarUrl"`
							AccountStatus       int         `json:"accountStatus"`
							Gender              int         `json:"gender"`
							City                int         `json:"city"`
							Birthday            int         `json:"birthday"`
							UserId              int         `json:"userId"`
							UserType            int         `json:"userType"`
							Nickname            string      `json:"nickname"`
							Signature           string      `json:"signature"`
							Description         string      `json:"description"`
							DetailDescription   string      `json:"detailDescription"`
							AvatarImgId         int64       `json:"avatarImgId"`
							BackgroundImgId     int64       `json:"backgroundImgId"`
							BackgroundUrl       string      `json:"backgroundUrl"`
							Authority           int         `json:"authority"`
							Mutual              bool        `json:"mutual"`
							ExpertTags          interface{} `json:"expertTags"`
							Experts             interface{} `json:"experts"`
							DjStatus            int         `json:"djStatus"`
							VipType             int         `json:"vipType"`
							RemarkName          interface{} `json:"remarkName"`
							AuthenticationTypes int         `json:"authenticationTypes"`
							AvatarDetail        interface{} `json:"avatarDetail"`
							AvatarImgIdStr      string      `json:"avatarImgIdStr"`
							Anchor              bool        `json:"anchor"`
							BackgroundImgIdStr  string      `json:"backgroundImgIdStr"`
							AvatarImgIdStr1     string      `json:"avatarImgId_str"`
						} `json:"userProfileData,omitempty"`
						Mlog struct {
							Id       string      `json:"id"`
							Type     int         `json:"type"`
							Position interface{} `json:"position"`
							Resource struct {
								MlogBaseData struct {
									Id              string      `json:"id"`
									Type            int         `json:"type"`
									Text            string      `json:"text"`
									InterveneText   string      `json:"interveneText"`
									PubTime         int64       `json:"pubTime"`
									CoverUrl        string      `json:"coverUrl"`
									CoverHeight     int         `json:"coverHeight"`
									CoverWidth      int         `json:"coverWidth"`
									CoverColor      int         `json:"coverColor"`
									CoverPicKey     string      `json:"coverPicKey"`
									CoverDynamicUrl interface{} `json:"coverDynamicUrl"`
									Audio           interface{} `json:"audio"`
									ThreadId        string      `json:"threadId"`
									Duration        int         `json:"duration"`
								} `json:"mlogBaseData"`
								MlogExtVO struct {
									LikedCount   int `json:"likedCount"`
									CommentCount int `json:"commentCount"`
									PlayCount    int `json:"playCount"`
									Song         struct {
										Id       int    `json:"id"`
										Name     string `json:"name"`
										CoverUrl string `json:"coverUrl"`
										Duration int    `json:"duration"`
										Artists  []struct {
											ArtistId   int    `json:"artistId"`
											ArtistName string `json:"artistName"`
										} `json:"artists"`
										Privilege interface{} `json:"privilege"`
										AlbumName string      `json:"albumName"`
										StartTime interface{} `json:"startTime"`
										EndTime   interface{} `json:"endTime"`
									} `json:"song"`
									CanCollect     bool          `json:"canCollect"`
									ArtistName     interface{}   `json:"artistName"`
									RcmdInfo       interface{}   `json:"rcmdInfo"`
									StrongPushMark interface{}   `json:"strongPushMark"`
									StrongPushIcon interface{}   `json:"strongPushIcon"`
									SpecialTag     interface{}   `json:"specialTag"`
									ChannelTag     string        `json:"channelTag"`
									Artists        []interface{} `json:"artists"`
								} `json:"mlogExtVO"`
								UserProfile struct {
									UserId    int    `json:"userId"`
									Nickname  string `json:"nickname"`
									AvatarUrl string `json:"avatarUrl"`
									Followed  bool   `json:"followed"`
									UserType  int    `json:"userType"`
									Anchor    bool   `json:"anchor"`
								} `json:"userProfile"`
								Status   int    `json:"status"`
								ShareUrl string `json:"shareUrl"`
							} `json:"resource"`
							Alg               interface{} `json:"alg"`
							Reason            interface{} `json:"reason"`
							MatchField        int         `json:"matchField"`
							MatchFieldContent interface{} `json:"matchFieldContent"`
							SameCity          bool        `json:"sameCity"`
						} `json:"mlog,omitempty"`
						VideoDuration  int    `json:"videoDuration,omitempty"`
						PublishTime    string `json:"publishTime,omitempty"`
						PlayCount      int    `json:"playCount,omitempty"`
						DjRadioProgram struct {
							MainSong struct {
								Name        string        `json:"name"`
								Id          int           `json:"id"`
								Position    int           `json:"position"`
								Alias       []interface{} `json:"alias"`
								Status      int           `json:"status"`
								RType       int           `json:"rType"`
								RUrl        interface{}   `json:"rUrl"`
								Fee         int           `json:"fee"`
								CopyrightId int           `json:"copyrightId"`
								MVId        int           `json:"mVId"`
								Disc        string        `json:"disc"`
								No          int           `json:"no"`
								Artists     []struct {
									Name        string        `json:"name"`
									Id          int           `json:"id"`
									PicId       int           `json:"picId"`
									Img1V1Id    int           `json:"img1v1Id"`
									BriefDesc   string        `json:"briefDesc"`
									PicUrl      string        `json:"picUrl"`
									Img1V1Url   string        `json:"img1v1Url"`
									AlbumSize   int           `json:"albumSize"`
									Alias       []interface{} `json:"alias"`
									Trans       string        `json:"trans"`
									MusicSize   int           `json:"musicSize"`
									TopicPerson int           `json:"topicPerson"`
								} `json:"artists"`
								Album struct {
									Name        string      `json:"name"`
									Id          int         `json:"id"`
									Type        interface{} `json:"type"`
									Size        int         `json:"size"`
									PicId       int64       `json:"picId"`
									BlurPicUrl  string      `json:"blurPicUrl"`
									CompanyId   int         `json:"companyId"`
									Pic         int64       `json:"pic"`
									PicUrl      string      `json:"picUrl"`
									PublishTime int         `json:"publishTime"`
									Description string      `json:"description"`
									Tags        string      `json:"tags"`
									Company     interface{} `json:"company"`
									BriefDesc   string      `json:"briefDesc"`
									Artist      struct {
										Name        string        `json:"name"`
										Id          int           `json:"id"`
										PicId       int           `json:"picId"`
										Img1V1Id    int           `json:"img1v1Id"`
										BriefDesc   string        `json:"briefDesc"`
										PicUrl      string        `json:"picUrl"`
										Img1V1Url   string        `json:"img1v1Url"`
										AlbumSize   int           `json:"albumSize"`
										Alias       []interface{} `json:"alias"`
										Trans       string        `json:"trans"`
										MusicSize   int           `json:"musicSize"`
										TopicPerson int           `json:"topicPerson"`
									} `json:"artist"`
									Songs           []interface{} `json:"songs"`
									Alias           []interface{} `json:"alias"`
									Status          int           `json:"status"`
									CopyrightId     int           `json:"copyrightId"`
									CommentThreadId string        `json:"commentThreadId"`
									Artists         []struct {
										Name        string        `json:"name"`
										Id          int           `json:"id"`
										PicId       int           `json:"picId"`
										Img1V1Id    int           `json:"img1v1Id"`
										BriefDesc   string        `json:"briefDesc"`
										PicUrl      string        `json:"picUrl"`
										Img1V1Url   string        `json:"img1v1Url"`
										AlbumSize   int           `json:"albumSize"`
										Alias       []interface{} `json:"alias"`
										Trans       string        `json:"trans"`
										MusicSize   int           `json:"musicSize"`
										TopicPerson int           `json:"topicPerson"`
									} `json:"artists"`
									SubType   interface{} `json:"subType"`
									TransName interface{} `json:"transName"`
									Mark      int         `json:"mark"`
								} `json:"album"`
								Starred         bool          `json:"starred"`
								Popularity      float64       `json:"popularity"`
								Score           int           `json:"score"`
								StarredNum      int           `json:"starredNum"`
								Duration        int           `json:"duration"`
								PlayedNum       int           `json:"playedNum"`
								DayPlays        int           `json:"dayPlays"`
								HearTime        int           `json:"hearTime"`
								Ringtone        interface{}   `json:"ringtone"`
								Crbt            interface{}   `json:"crbt"`
								MP3Url          interface{}   `json:"mP3Url"`
								Audition        interface{}   `json:"audition"`
								CopyFrom        string        `json:"copyFrom"`
								CommentThreadId string        `json:"commentThreadId"`
								RtUrl           interface{}   `json:"rtUrl"`
								Ftype           int           `json:"ftype"`
								RtUrls          []interface{} `json:"rtUrls"`
								Copyright       int           `json:"copyright"`
								TransName       interface{}   `json:"transName"`
								Sign            interface{}   `json:"sign"`
								Mark            int           `json:"mark"`
								NoCopyrightRcmd interface{}   `json:"noCopyrightRcmd"`
								Lmusic          interface{}   `json:"lmusic"`
								Hmusic          interface{}   `json:"hmusic"`
								Mmusic          interface{}   `json:"mmusic"`
								Bmusic          interface{}   `json:"bmusic"`
							} `json:"mainSong"`
							Songs interface{} `json:"songs"`
							Dj    struct {
								DefaultAvatar     bool        `json:"defaultAvatar"`
								Province          int         `json:"province"`
								AuthStatus        int         `json:"authStatus"`
								Followed          bool        `json:"followed"`
								AvatarUrl         string      `json:"avatarUrl"`
								AccountStatus     int         `json:"accountStatus"`
								Gender            int         `json:"gender"`
								City              int         `json:"city"`
								Birthday          int64       `json:"birthday"`
								UserId            int         `json:"userId"`
								UserType          int         `json:"userType"`
								Nickname          string      `json:"nickname"`
								Signature         string      `json:"signature"`
								Description       string      `json:"description"`
								DetailDescription string      `json:"detailDescription"`
								AvatarImgId       int64       `json:"avatarImgId"`
								BackgroundImgId   int64       `json:"backgroundImgId"`
								BackgroundUrl     string      `json:"backgroundUrl"`
								Authority         int         `json:"authority"`
								Mutual            bool        `json:"mutual"`
								ExpertTags        interface{} `json:"expertTags"`
								Experts           interface{} `json:"experts"`
								DjStatus          int         `json:"djStatus"`
								VipType           int         `json:"vipType"`
								RemarkName        interface{} `json:"remarkName"`
								Brand             string      `json:"brand"`
							} `json:"dj"`
							BlurCoverUrl interface{} `json:"blurCoverUrl"`
							Radio        struct {
								Id                    int         `json:"id"`
								Dj                    interface{} `json:"dj"`
								Name                  string      `json:"name"`
								PicUrl                string      `json:"picUrl"`
								Desc                  string      `json:"desc"`
								SubCount              int         `json:"subCount"`
								ProgramCount          int         `json:"programCount"`
								CreateTime            int64       `json:"createTime"`
								CategoryId            int         `json:"categoryId"`
								Category              string      `json:"category"`
								RadioFeeType          int         `json:"radioFeeType"`
								FeeScope              int         `json:"feeScope"`
								Buyed                 bool        `json:"buyed"`
								Videos                interface{} `json:"videos"`
								Finished              bool        `json:"finished"`
								UnderShelf            bool        `json:"underShelf"`
								PurchaseCount         int         `json:"purchaseCount"`
								Price                 int         `json:"price"`
								OriginalPrice         int         `json:"originalPrice"`
								DiscountPrice         interface{} `json:"discountPrice"`
								LastProgramCreateTime int64       `json:"lastProgramCreateTime"`
								LastProgramName       interface{} `json:"lastProgramName"`
								LastProgramId         int         `json:"lastProgramId"`
								PicId                 int64       `json:"picId"`
								RcmdText              interface{} `json:"rcmdText"`
								HightQuality          bool        `json:"hightQuality"`
								WhiteList             bool        `json:"whiteList"`
								ComposeVideo          bool        `json:"composeVideo"`
							} `json:"radio"`
							SubscribedCount   int           `json:"subscribedCount"`
							Reward            bool          `json:"reward"`
							MainTrackId       int           `json:"mainTrackId"`
							SerialNum         int           `json:"serialNum"`
							ListenerCount     int           `json:"listenerCount"`
							Name              string        `json:"name"`
							Id                int           `json:"id"`
							CreateTime        int64         `json:"createTime"`
							Description       string        `json:"description"`
							UserId            int           `json:"userId"`
							CoverUrl          string        `json:"coverUrl"`
							CommentThreadId   string        `json:"commentThreadId"`
							Channels          []interface{} `json:"channels"`
							Titbits           interface{}   `json:"titbits"`
							TitbitImages      interface{}   `json:"titbitImages"`
							PubStatus         int           `json:"pubStatus"`
							TrackCount        int           `json:"trackCount"`
							BdAuditStatus     int           `json:"bdAuditStatus"`
							DisPlayStatus     string        `json:"disPlayStatus"`
							ProgramFeeType    int           `json:"programFeeType"`
							Buyed             bool          `json:"buyed"`
							ProgramDesc       interface{}   `json:"programDesc"`
							H5Links           []interface{} `json:"h5Links"`
							CoverId           int64         `json:"coverId"`
							AdjustedPlayCount float64       `json:"adjustedPlayCount"`
							CanReward         bool          `json:"canReward"`
							AuditStatus       int           `json:"auditStatus"`
							Duration          int           `json:"duration"`
							Publish           bool          `json:"publish"`
						} `json:"djRadioProgram,omitempty"`
						VoiceIcon struct {
							Type  interface{} `json:"type"`
							Value interface{} `json:"value"`
						} `json:"voiceIcon,omitempty"`
						DjProgramCount int `json:"djProgramCount,omitempty"`
						Comments       []struct {
							ResourceType int         `json:"resourceType"`
							Time         int64       `json:"time"`
							Content      string      `json:"content"`
							CombindId    interface{} `json:"combindId"`
							User         struct {
								LocationInfo        interface{} `json:"locationInfo"`
								LiveInfo            interface{} `json:"liveInfo"`
								Anonym              int         `json:"anonym"`
								UserId              int         `json:"userId"`
								UserType            int         `json:"userType"`
								Nickname            string      `json:"nickname"`
								AvatarImgId         int64       `json:"avatarImgId"`
								AvatarUrl           string      `json:"avatarUrl"`
								BackgroundImgId     int64       `json:"backgroundImgId"`
								BackgroundUrl       string      `json:"backgroundUrl"`
								Signature           string      `json:"signature"`
								CreateTime          int64       `json:"createTime"`
								UserName            string      `json:"userName"`
								AccountType         int         `json:"accountType"`
								ShortUserName       string      `json:"shortUserName"`
								Birthday            int64       `json:"birthday"`
								Authority           int         `json:"authority"`
								Gender              int         `json:"gender"`
								AccountStatus       int         `json:"accountStatus"`
								Province            int         `json:"province"`
								City                int         `json:"city"`
								AuthStatus          int         `json:"authStatus"`
								Description         string      `json:"description"`
								DetailDescription   string      `json:"detailDescription"`
								DefaultAvatar       bool        `json:"defaultAvatar"`
								ExpertTags          interface{} `json:"expertTags"`
								Experts             interface{} `json:"experts"`
								DjStatus            int         `json:"djStatus"`
								LocationStatus      int         `json:"locationStatus"`
								VipType             int         `json:"vipType"`
								Followed            bool        `json:"followed"`
								Mutual              bool        `json:"mutual"`
								Authenticated       bool        `json:"authenticated"`
								LastLoginTime       int64       `json:"lastLoginTime"`
								LastLoginIP         string      `json:"lastLoginIP"`
								RemarkName          interface{} `json:"remarkName"`
								ViptypeVersion      int64       `json:"viptypeVersion"`
								AuthenticationTypes int         `json:"authenticationTypes"`
								VipRights           interface{} `json:"vipRights"`
							} `json:"user"`
							BeRepliedUser          interface{} `json:"beRepliedUser"`
							Liked                  bool        `json:"liked"`
							LikedCount             int         `json:"likedCount"`
							ResourceInfo           string      `json:"resourceInfo"`
							CommentId              int64       `json:"commentId"`
							ThreadId               string      `json:"threadId"`
							BeRepliedContent       interface{} `json:"beRepliedContent"`
							ExpressionUrl          interface{} `json:"expressionUrl"`
							BeRepliedExpressionUrl interface{} `json:"beRepliedExpressionUrl"`
							ParentCommentId        int         `json:"parentCommentId"`
						} `json:"comments,omitempty"`
					} `json:"resourceExt"`
					ResourcePolicyId string `json:"resourcePolicyId"`
					Action           struct {
						ClickAction struct {
							Action    int    `json:"action"`
							TargetUrl string `json:"targetUrl"`
						} `json:"clickAction"`
					} `json:"action"`
					UiElement struct {
						MainTitle struct {
							Title       string      `json:"title"`
							TitleImgId  interface{} `json:"titleImgId"`
							TitleImgUrl interface{} `json:"titleImgUrl"`
							Action      interface{} `json:"action"`
						} `json:"mainTitle"`
						SubTitles []struct {
							Title       string      `json:"title"`
							TitleImgId  interface{} `json:"titleImgId"`
							TitleImgUrl interface{} `json:"titleImgUrl"`
							Action      interface{} `json:"action"`
						} `json:"subTitles"`
						Images []struct {
							Tag         interface{} `json:"tag"`
							Title       interface{} `json:"title"`
							Superscript interface{} `json:"superscript"`
							ImageId     int         `json:"imageId"`
							ImageUrl    string      `json:"imageUrl"`
							Md5         interface{} `json:"md5"`
							Width       int         `json:"width"`
							Height      int         `json:"height"`
							Action      interface{} `json:"action"`
						} `json:"images"`
						Labels    interface{} `json:"labels"`
						TextLinks []struct {
							Tag  interface{} `json:"tag"`
							Text string      `json:"text"`
							Url  interface{} `json:"url"`
						} `json:"textLinks"`
						Descriptions []struct {
							Tag         interface{} `json:"tag"`
							Description string      `json:"description"`
						} `json:"descriptions"`
						Icons []struct {
							Tag    interface{} `json:"tag"`
							ImgId  int         `json:"imgId"`
							ImgUrl string      `json:"imgUrl"`
						} `json:"icons"`
						Buttons []struct {
							Tag      interface{} `json:"tag"`
							Text     string      `json:"text"`
							ImageUrl interface{} `json:"imageUrl"`
							Action   struct {
								ClickAction struct {
									Action    int    `json:"action"`
									TargetUrl string `json:"targetUrl"`
								} `json:"clickAction"`
							} `json:"action"`
						} `json:"buttons"`
						Videos      interface{} `json:"videos"`
						Superscript interface{} `json:"superscript"`
						Type        string      `json:"type"`
						CoverTagVO  interface{} `json:"coverTagVO"`
					} `json:"uiElement"`
					Valid         bool        `json:"valid"`
					Alg           interface{} `json:"alg"`
					Scm           interface{} `json:"scm"`
					VisibleStatus string      `json:"visibleStatus"`
				} `json:"resources"`
			} `json:"creatives"`
			CanRefresh    bool        `json:"canRefresh"`
			VisibleStatus string      `json:"visibleStatus"`
			BlockConfig   interface{} `json:"blockConfig"`
			BlockCursor   interface{} `json:"blockCursor"`
			HasMore       bool        `json:"hasMore"`
			BlockParam    interface{} `json:"blockParam"`
		} `json:"blocks"`
		HasMore    bool `json:"hasMore"`
		PageConfig struct {
			RefreshToast interface{} `json:"refreshToast"`
			NodataToast  interface{} `json:"nodataToast"`
			Title        string      `json:"title"`
			Fullscreen   bool        `json:"fullscreen"`
			Abtest       interface{} `json:"abtest"`
		} `json:"pageConfig"`
		PageCodeContext struct {
			PageCode      string `json:"pageCode"`
			BlockValidMap struct {
				PERSONALCREATEVOICE     bool `json:"PERSONAL_CREATE_VOICE"`
				PERSONALALBUMRACKBLOCK  bool `json:"PERSONAL_ALBUM_RACK_BLOCK"`
				PERSONALMYCIRCLE        bool `json:"PERSONAL_MY_CIRCLE"`
				PERSONALMUSICTASTE      bool `json:"PERSONAL_MUSIC_TASTE"`
				PERSONALSHOWCASEBLOCK   bool `json:"PERSONAL_SHOWCASE_BLOCK"`
				PERSONALMYMLOG          bool `json:"PERSONAL_MY_MLOG"`
				ARTISTREPRESENTLYRIC    bool `json:"ARTIST_REPRESENT_LYRIC"`
				PERSONALMUSICBOARD      bool `json:"PERSONAL_MUSIC_BOARD"`
				PERSONALTALENTPLAYLIST  bool `json:"PERSONAL_TALENT_PLAYLIST"`
				PERSONALTALENTVOICE     bool `json:"PERSONAL_TALENT_VOICE"`
				PERSONALARTISTBASIC     bool `json:"PERSONAL_ARTIST_BASIC"`
				PERSONALRCMDARTIST      bool `json:"PERSONAL_RCMD_ARTIST"`
				PERSONALCOLLECTPLAYLIST bool `json:"PERSONAL_COLLECT_PLAYLIST"`
				PERSONALTALENTMLOG      bool `json:"PERSONAL_TALENT_MLOG"`
				PERSONALCREATEPLAYLIST  bool `json:"PERSONAL_CREATE_PLAYLIST"`
				ARTISTREPRESENTSONG     bool `json:"ARTIST_REPRESENT_SONG"`
				PERSONALUSERBASIC       bool `json:"PERSONAL_USER_BASIC"`
				ARTISTPARTNER           bool `json:"ARTIST_PARTNER"`
				PERSONALMUSICTOPIC      bool `json:"PERSONAL_MUSIC_TOPIC"`
				PERSONALTALENTKSONG     bool `json:"PERSONAL_TALENT_KSONG"`
				PERSONALWISHLISTBLOCK   bool `json:"PERSONAL_WISH_LIST_BLOCK"`
				PERSONALMYCOMMENT       bool `json:"PERSONAL_MY_COMMENT"`
				PERSONALCREATEVOICELIST bool `json:"PERSONAL_CREATE_VOICE_LIST"`
				PERSONALMYKSONG         bool `json:"PERSONAL_MY_KSONG"`
			} `json:"blockValidMap"`
			BlockFlagMap struct {
				MYFAVORITE struct {
					VisibleStatus interface{} `json:"visibleStatus"`
				} `json:"MY_FAVORITE"`
				PERSONALCREATEVOICE struct {
					VisibleStatus interface{} `json:"visibleStatus"`
				} `json:"PERSONAL_CREATE_VOICE"`
				PERSONALCREATEPLAYLIST struct {
					VisibleStatus interface{} `json:"visibleStatus"`
				} `json:"PERSONAL_CREATE_PLAYLIST"`
				LISTENRANK struct {
					VisibleStatus string `json:"visibleStatus"`
				} `json:"LISTEN_RANK"`
				PERSONALMYMLOG struct {
					VisibleStatus interface{} `json:"visibleStatus"`
				} `json:"PERSONAL_MY_MLOG"`
				COMMONINTEREST struct {
					VisibleStatus interface{} `json:"visibleStatus"`
				} `json:"COMMON_INTEREST"`
				PERSONALMYCOMMENT struct {
					VisibleStatus string `json:"visibleStatus"`
				} `json:"PERSONAL_MY_COMMENT"`
				PERSONALCOLLECTPLAYLIST struct {
					VisibleStatus interface{} `json:"visibleStatus"`
				} `json:"PERSONAL_COLLECT_PLAYLIST"`
				PERSONALCREATEVOICELIST struct {
					VisibleStatus interface{} `json:"visibleStatus"`
				} `json:"PERSONAL_CREATE_VOICE_LIST"`
				PERSONALMYKSONG struct {
					VisibleStatus interface{} `json:"visibleStatus"`
				} `json:"PERSONAL_MY_KSONG"`
			} `json:"blockFlagMap"`
			MusicTasteValidMap struct {
				MYFAVORITE     bool `json:"MY_FAVORITE"`
				LISTENRANK     bool `json:"LISTEN_RANK"`
				COMMONINTEREST bool `json:"COMMON_INTEREST"`
			} `json:"musicTasteValidMap"`
			UserId                   int         `json:"userId"`
			ArtistId                 int         `json:"artistId"`
			Expert                   bool        `json:"expert"`
			PlayListExpertLevel      interface{} `json:"playListExpertLevel"`
			PlayListExpertPlayNum    interface{} `json:"playListExpertPlayNum"`
			PlayListExpertCollectNum interface{} `json:"playListExpertCollectNum"`
			VoiceExpertPlayNum       interface{} `json:"voiceExpertPlayNum"`
			VoiceExpertLikedNum      interface{} `json:"voiceExpertLikedNum"`
			OutputTags               interface{} `json:"outputTags"`
			VoiceExpertLevel         interface{} `json:"voiceExpertLevel"`
			MLogExpertLevel          interface{} `json:"mLogExpertLevel"`
			FirstExpertBlockCode     interface{} `json:"firstExpertBlockCode"`
			PlayListExpertIcon       interface{} `json:"playListExpertIcon"`
			PlayListExpertIconUrl    interface{} `json:"playListExpertIconUrl"`
			VoiceExpertIcon          interface{} `json:"voiceExpertIcon"`
			VoiceExpertIconUrl       interface{} `json:"voiceExpertIconUrl"`
			VisitorId                int         `json:"visitorId"`
			AbTestGroup              interface{} `json:"abTestGroup"`
			ClientVersion            int64       `json:"clientVersion"`
			ClientType               string      `json:"clientType"`
			ExpertRankDTO            interface{} `json:"expertRankDTO"`
			VoiceGuidePageUrl        interface{} `json:"voiceGuidePageUrl"`
			VoiceGuideText           interface{} `json:"voiceGuideText"`
			Follow                   bool        `json:"follow"`
			ClosePersonalizedRcmd    bool        `json:"closePersonalizedRcmd"`
			ReverseFollow            bool        `json:"reverseFollow"`
		} `json:"pageCodeContext"`
	} `json:"data"`
	Message string `json:"message"`
}
